name = "Melon SMP"
author = "Melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15090c3746eebf20688e61f8415640395d5150a2b75c683540d18b80ed5902b1"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
