name = "Melon SMP"
author = "Melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f84b923bd6b90c3c9a993fa5911367c0189208bdff8add1d988894e5247710d"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
