name = "Melon SMP"
author = "Melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bfa1262ff6e0f3e8f02b1cd89d1cbada1516381361e1fb27787f24384693987"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
